name: lint

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'pylintrc'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'pylintrc'

jobs:

  pylint:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          pip install -e .
          pip install pylint

      - name: Lint
        run: pylint --fail-under=0 --fail-on=E --recursive=y .
        # For local env, you might want to pass --ignore-paths=venv
